package edu.aku.abdulsajid.vasa2018.utils;

/*import com.google.common.collect.HashMultimap;
import com.google.common.collect.Multimap;*/

/**
 * Created by Umeed-e-Nau on 12/21/2016.
 */
public class Ucs {

/*    private static Multimap<String, String> edu.aku.abdulsajid.VASMonitring.data = HashMultimap.create();

    public static List<String> get(String tehsil) {

        edu.aku.abdulsajid.VASMonitring.data.put("Ali Pur", "Alipur City");
        edu.aku.abdulsajid.VASMonitring.data.put("Ali Pur", "Aliwali");
        edu.aku.abdulsajid.VASMonitring.data.put("Ali Pur", "Alpuri");
        edu.aku.abdulsajid.VASMonitring.data.put("Ali Pur", "Bait Mullanwali");
        edu.aku.abdulsajid.VASMonitring.data.put("Ali Pur", "Bazwala");
        edu.aku.abdulsajid.VASMonitring.data.put("Ali Pur", "Bunerwal");
        edu.aku.abdulsajid.VASMonitring.data.put("Ali Pur", "Butyal");
        edu.aku.abdulsajid.VASMonitring.data.put("Ali Pur", "Chakensar");
        edu.aku.abdulsajid.VASMonitring.data.put("Ali Pur", "Damorai");
        edu.aku.abdulsajid.VASMonitring.data.put("Ali Pur", "Dandai");
        edu.aku.abdulsajid.VASMonitring.data.put("Ali Pur", "Debrai");
        edu.aku.abdulsajid.VASMonitring.data.put("Ali Pur", "Fatehpur Janubi");
        edu.aku.abdulsajid.VASMonitring.data.put("Ali Pur", "Ghalwan");
        edu.aku.abdulsajid.VASMonitring.data.put("Ali Pur", "Khairpur Sadat");
        edu.aku.abdulsajid.VASMonitring.data.put("Ali Pur", "Khangarh Doam");
        edu.aku.abdulsajid.VASMonitring.data.put("Ali Pur", "Kuz Kana");
        edu.aku.abdulsajid.VASMonitring.data.put("Ali Pur", "Langarwah");
        edu.aku.abdulsajid.VASMonitring.data.put("Ali Pur", "Lilowani");
        edu.aku.abdulsajid.VASMonitring.data.put("Ali Pur", "Maira");
        edu.aku.abdulsajid.VASMonitring.data.put("Ali Pur", "Malik Kheil");
        edu.aku.abdulsajid.VASMonitring.data.put("Ali Pur", "Mudawala");
        edu.aku.abdulsajid.VASMonitring.data.put("Ali Pur", "Muradpur Janubi");
        edu.aku.abdulsajid.VASMonitring.data.put("Ali Pur", "Opal");
        edu.aku.abdulsajid.VASMonitring.data.put("Ali Pur", "Pirabad");
        edu.aku.abdulsajid.VASMonitring.data.put("Ali Pur", "Pir Khana");
        edu.aku.abdulsajid.VASMonitring.data.put("Ali Pur", "Sarkool");
        edu.aku.abdulsajid.VASMonitring.data.put("Ali Pur", "Seetpur");
        edu.aku.abdulsajid.VASMonitring.data.put("Ali Pur", "Shahpur");
        edu.aku.abdulsajid.VASMonitring.data.put("Ali Pur", "Sultanpur");
        edu.aku.abdulsajid.VASMonitring.data.put("Ali Pur", "Yakaywalai	");
        edu.aku.abdulsajid.VASMonitring.data.put("Badin", "Luhnwari Sharif	");
        edu.aku.abdulsajid.VASMonitring.data.put("Badin", "Kadhan	");
        edu.aku.abdulsajid.VASMonitring.data.put("Badin", "Mithi-III	");
        edu.aku.abdulsajid.VASMonitring.data.put("Badin", "Kadhan	");
        edu.aku.abdulsajid.VASMonitring.data.put("Badin", "Mithi-III	");
        edu.aku.abdulsajid.VASMonitring.data.put("Badin", "Bhugra Memon	");
        edu.aku.abdulsajid.VASMonitring.data.put("Badin", "Luhnwari Sharif	");
        edu.aku.abdulsajid.VASMonitring.data.put("Badin", "Abdullah Shah	");
        edu.aku.abdulsajid.VASMonitring.data.put("Badin", "Abdullah Shah	");
        edu.aku.abdulsajid.VASMonitring.data.put("Badin", "Abdullah Shah	");
        edu.aku.abdulsajid.VASMonitring.data.put("Badin", "Muhammad Khan Burghari	");
        edu.aku.abdulsajid.VASMonitring.data.put("Badin", "Kadi Kazia	");
        edu.aku.abdulsajid.VASMonitring.data.put("Badin", "Kadi Kazia	");
        edu.aku.abdulsajid.VASMonitring.data.put("Badin", "Seerani	");
        edu.aku.abdulsajid.VASMonitring.data.put("Badin", "Bhugra Memon	");
        edu.aku.abdulsajid.VASMonitring.data.put("Badin", "Seerani	");
        edu.aku.abdulsajid.VASMonitring.data.put("Badin", "Seerani	");
        edu.aku.abdulsajid.VASMonitring.data.put("Badin", "Bhugra Memon	");
        edu.aku.abdulsajid.VASMonitring.data.put("Badin", "Nindo	");
        edu.aku.abdulsajid.VASMonitring.data.put("Badin", "Mithi-III	");
        edu.aku.abdulsajid.VASMonitring.data.put("Badin", "Nindo	");
        edu.aku.abdulsajid.VASMonitring.data.put("Badin", "Badin-I	");
        edu.aku.abdulsajid.VASMonitring.data.put("Badin", "Badin-III	");
        edu.aku.abdulsajid.VASMonitring.data.put("Badin", "Kadi Kazia	");
        edu.aku.abdulsajid.VASMonitring.data.put("Badin", "Badin-II	");
        edu.aku.abdulsajid.VASMonitring.data.put("Badin", "Badin-III	");
        edu.aku.abdulsajid.VASMonitring.data.put("Badin", "Muhammad Khan Bhurguri	");
        edu.aku.abdulsajid.VASMonitring.data.put("Badin", "Lunwari Sharif	");
        edu.aku.abdulsajid.VASMonitring.data.put("Bela", "Bela City	");
        edu.aku.abdulsajid.VASMonitring.data.put("Bela", "Wallpat	");
        edu.aku.abdulsajid.VASMonitring.data.put("Bela", "Kathore	");
        edu.aku.abdulsajid.VASMonitring.data.put("Bela", "Gadore	");
        edu.aku.abdulsajid.VASMonitring.data.put("Bela", "Wallpat North	");
        edu.aku.abdulsajid.VASMonitring.data.put("Bela", "Gadore	");
        edu.aku.abdulsajid.VASMonitring.data.put("Bela", "Kathore	");
        edu.aku.abdulsajid.VASMonitring.data.put("Bela", "Gadore	");
        edu.aku.abdulsajid.VASMonitring.data.put("Bela", "Wallpat North	");
        edu.aku.abdulsajid.VASMonitring.data.put("Bela", "Kathore	");
        edu.aku.abdulsajid.VASMonitring.data.put("Chatter", "Shori Drabhi	");
        edu.aku.abdulsajid.VASMonitring.data.put("Chatter", "Shah Pur	");
        edu.aku.abdulsajid.VASMonitring.data.put("Chatter", "Doulat Ghari	");
        edu.aku.abdulsajid.VASMonitring.data.put("Chatter", "Shori Drabhi	");
        edu.aku.abdulsajid.VASMonitring.data.put("Chatter", "Mir Nabi Bux Khosa	");
        edu.aku.abdulsajid.VASMonitring.data.put("Chatter", "Doulat Ghari	");
        edu.aku.abdulsajid.VASMonitring.data.put("Chatter", "Doulat Ghari");
        edu.aku.abdulsajid.VASMonitring.data.put("Dera Murad Jamali", "Jhudair North	");
        edu.aku.abdulsajid.VASMonitring.data.put("Dera Murad Jamali", "Quba Sher Khan	");
        edu.aku.abdulsajid.VASMonitring.data.put("Dera Murad Jamali", "Jhudair North	");
        edu.aku.abdulsajid.VASMonitring.data.put("Dera Murad Jamali", "Manjhoti 1	");
        edu.aku.abdulsajid.VASMonitring.data.put("Dera Murad Jamali", "Manjhoti 2	");
        edu.aku.abdulsajid.VASMonitring.data.put("Dera Murad Jamali", "Manjhoti 1	");
        edu.aku.abdulsajid.VASMonitring.data.put("Dera Murad Jamali", "Manjhothi	");
        edu.aku.abdulsajid.VASMonitring.data.put("Dera Murad Jamali", "Jhudair North	");
        edu.aku.abdulsajid.VASMonitring.data.put("Dera Murad Jamali", "Gharbi	");
        edu.aku.abdulsajid.VASMonitring.data.put("Dera Murad Jamali", "Bedar	");
        edu.aku.abdulsajid.VASMonitring.data.put("Dera Murad Jamali", "Gharbi	");
        edu.aku.abdulsajid.VASMonitring.data.put("Dureji", "Lohi	");
        edu.aku.abdulsajid.VASMonitring.data.put("Dureji", "Duraje	");
        edu.aku.abdulsajid.VASMonitring.data.put("Dureji", "Lohi	");
        edu.aku.abdulsajid.VASMonitring.data.put("Gaddani", "Gaddani	");
        edu.aku.abdulsajid.VASMonitring.data.put("Gandakha", "Kariapheri	");
        edu.aku.abdulsajid.VASMonitring.data.put("Gandakha", "Sobdrani 1	");
        edu.aku.abdulsajid.VASMonitring.data.put("Gandakha", "Gandakha	");
        edu.aku.abdulsajid.VASMonitring.data.put("Gandakha", "Sobdrani 1	");
        edu.aku.abdulsajid.VASMonitring.data.put("Gandakha", "Ahmedabad	");
        edu.aku.abdulsajid.VASMonitring.data.put("Gandakha", "Bagh Head	");
        edu.aku.abdulsajid.VASMonitring.data.put("Gandakha", "Sibi Jadeed	");
        edu.aku.abdulsajid.VASMonitring.data.put("Gandakha", "Bagh Head	");
        edu.aku.abdulsajid.VASMonitring.data.put("Gandakha", "Bagh Head	");
        edu.aku.abdulsajid.VASMonitring.data.put("Gandakha", "Gandakha	");
        edu.aku.abdulsajid.VASMonitring.data.put("Gandakha", "Sobdrani 1	");
        edu.aku.abdulsajid.VASMonitring.data.put("Gandakha", "Noshki Jadeed	");
        edu.aku.abdulsajid.VASMonitring.data.put("Gandakha", "Janan	");
        edu.aku.abdulsajid.VASMonitring.data.put("Gandakha", "Sobdrani 1	");
        edu.aku.abdulsajid.VASMonitring.data.put("Gandakha", "Bagh Head	");
        edu.aku.abdulsajid.VASMonitring.data.put("Golarchi", "Dubi	");
        edu.aku.abdulsajid.VASMonitring.data.put("Golarchi", "Khorwaah	");
        edu.aku.abdulsajid.VASMonitring.data.put("Golarchi", "Gharo	");
        edu.aku.abdulsajid.VASMonitring.data.put("Golarchi", "Tarai	");
        edu.aku.abdulsajid.VASMonitring.data.put("Golarchi", "Gharo	");
        edu.aku.abdulsajid.VASMonitring.data.put("Golarchi", "Khorwaah	");
        edu.aku.abdulsajid.VASMonitring.data.put("Golarchi", "Karyo Ganhwar	");
        edu.aku.abdulsajid.VASMonitring.data.put("Golarchi", "Rahuki	");
        edu.aku.abdulsajid.VASMonitring.data.put("Golarchi", "Karyo Ganhwar	");
        edu.aku.abdulsajid.VASMonitring.data.put("Golarchi", "Dubi	");
        edu.aku.abdulsajid.VASMonitring.data.put("Golarchi", "Dubi	");
        edu.aku.abdulsajid.VASMonitring.data.put("Golarchi", "Ahmed Raju	");
        edu.aku.abdulsajid.VASMonitring.data.put("Golarchi", "Golarchi	");
        edu.aku.abdulsajid.VASMonitring.data.put("Golarchi", "Gharro	");
        edu.aku.abdulsajid.VASMonitring.data.put("Golarchi", "Tarai	");
        edu.aku.abdulsajid.VASMonitring.data.put("Golarchi", "Gharro	");
        edu.aku.abdulsajid.VASMonitring.data.put("Hub", "Wander	");
        edu.aku.abdulsajid.VASMonitring.data.put("Hub", "Sakran	");
        edu.aku.abdulsajid.VASMonitring.data.put("Hub", "Gaddani	");
        edu.aku.abdulsajid.VASMonitring.data.put("Hub", "Sakran	");
        edu.aku.abdulsajid.VASMonitring.data.put("Hub", "Barote	");
        edu.aku.abdulsajid.VASMonitring.data.put("Hub", "Gaddani	");
        edu.aku.abdulsajid.VASMonitring.data.put("Hub", "Gaddani	");
        edu.aku.abdulsajid.VASMonitring.data.put("Hub", "Sakran	");
        edu.aku.abdulsajid.VASMonitring.data.put("Jaam Nawaz Ali", "Jaam Nawaz Ali	");
        edu.aku.abdulsajid.VASMonitring.data.put("Jaam Nawaz Ali", "Berani	");
        edu.aku.abdulsajid.VASMonitring.data.put("Jaam Nawaz Ali", "Jaam Nawaz Ali	");
        edu.aku.abdulsajid.VASMonitring.data.put("Jaam Nawaz Ali", "Hot Wassan	");
        edu.aku.abdulsajid.VASMonitring.data.put("Jaam Nawaz Ali", "Nau Abad	");
        edu.aku.abdulsajid.VASMonitring.data.put("Jaam Nawaz Ali", "Nau Abad	");
        edu.aku.abdulsajid.VASMonitring.data.put("Jaam Nawaz Ali", "Jaam Nawaz Ali	");
        edu.aku.abdulsajid.VASMonitring.data.put("Jatoi", "Bair Bund	");
        edu.aku.abdulsajid.VASMonitring.data.put("Jatoi", "Bair Mir Hazar Khan B	");
        edu.aku.abdulsajid.VASMonitring.data.put("Jatoi", "Bakani	");
        edu.aku.abdulsajid.VASMonitring.data.put("Jatoi", "Belaywala	");
        edu.aku.abdulsajid.VASMonitring.data.put("Jatoi", "Binda Ishaq	");
        edu.aku.abdulsajid.VASMonitring.data.put("Jatoi", "Dammer Wala Shumali	");
        edu.aku.abdulsajid.VASMonitring.data.put("Jatoi", "Jatoi City	");
        edu.aku.abdulsajid.VASMonitring.data.put("Jatoi", "Jatoi Shumali	");
        edu.aku.abdulsajid.VASMonitring.data.put("Jatoi", "Jehlarin	");
        edu.aku.abdulsajid.VASMonitring.data.put("Jatoi", "Jhuggiwala	");
        edu.aku.abdulsajid.VASMonitring.data.put("Jatoi", "Kotla Gamoon	");
        edu.aku.abdulsajid.VASMonitring.data.put("Jatoi", "Rampur	");
        edu.aku.abdulsajid.VASMonitring.data.put("Jatoi", "Sabaywala	");
        edu.aku.abdulsajid.VASMonitring.data.put("Jatoi", "Sehrah Sultan City	");
        edu.aku.abdulsajid.VASMonitring.data.put("Jatoi", "Shahbazpur	");
        edu.aku.abdulsajid.VASMonitring.data.put("Jatoi", "Vanis	");
        edu.aku.abdulsajid.VASMonitring.data.put("Jhat Pat", "Sathi	");
        edu.aku.abdulsajid.VASMonitring.data.put("Jhat Pat", "Taj Pur	");
        edu.aku.abdulsajid.VASMonitring.data.put("Jhat Pat", "UC 1	");
        edu.aku.abdulsajid.VASMonitring.data.put("Jhat Pat", "Band Manik	");
        edu.aku.abdulsajid.VASMonitring.data.put("Jhat Pat", "Manjhothi	");
        edu.aku.abdulsajid.VASMonitring.data.put("Jhat Pat", "Cattle Farm 	");
        edu.aku.abdulsajid.VASMonitring.data.put("Jhat Pat", "Cattle Farm 	");
        edu.aku.abdulsajid.VASMonitring.data.put("Jhat Pat", "Chalgri	");
        edu.aku.abdulsajid.VASMonitring.data.put("Jhat pat", "Ward No. 12	");
        edu.aku.abdulsajid.VASMonitring.data.put("Jhat Pat", "Rojhan Jamali	");
        edu.aku.abdulsajid.VASMonitring.data.put("Jhat Pat", "Ramzepur	");
        edu.aku.abdulsajid.VASMonitring.data.put("Jhat Pat", "UC 1	");
        edu.aku.abdulsajid.VASMonitring.data.put("Jhat Pat", "Hafeezabad	");
        edu.aku.abdulsajid.VASMonitring.data.put("Jhat Pat", "Cattle farm	");
        edu.aku.abdulsajid.VASMonitring.data.put("Kanraj", "Kanraj	");
        edu.aku.abdulsajid.VASMonitring.data.put("Kanraj", "Kanraj	");
        edu.aku.abdulsajid.VASMonitring.data.put("Khan Pur", "Azim Shah	");
        edu.aku.abdulsajid.VASMonitring.data.put("Khan Pur", "Bgho Bahar	");
        edu.aku.abdulsajid.VASMonitring.data.put("Khan Pur", "Chachran Sharif	");
        edu.aku.abdulsajid.VASMonitring.data.put("Khan Pur", "Chank No. 45/P	");
        edu.aku.abdulsajid.VASMonitring.data.put("Khan Pur", "Chandia	");
        edu.aku.abdulsajid.VASMonitring.data.put("Khan Pur", "Dinpur Sharif	");
        edu.aku.abdulsajid.VASMonitring.data.put("Khan Pur", "Ghari Iftikhar Khan	");
        edu.aku.abdulsajid.VASMonitring.data.put("Khan Pur", "Ghazipur	");
        edu.aku.abdulsajid.VASMonitring.data.put("Khan Pur", "Ghena Lar (H.Q. Jangi)	");
        edu.aku.abdulsajid.VASMonitring.data.put("Khan Pur", "Islam Garh	");
        edu.aku.abdulsajid.VASMonitring.data.put("Khan Pur", "Jajja Abbasian	");
        edu.aku.abdulsajid.VASMonitring.data.put("Khan Pur", "Jetha Bhutta	");
        edu.aku.abdulsajid.VASMonitring.data.put("Khan Pur", "Jhoran	");
        edu.aku.abdulsajid.VASMonitring.data.put("Khan Pur", "Kotla Pathan	");
        edu.aku.abdulsajid.VASMonitring.data.put("Khan Pur", "Latki	");
        edu.aku.abdulsajid.VASMonitring.data.put("Khan Pur", "Mari Allah Bachaya	");
        edu.aku.abdulsajid.VASMonitring.data.put("Khan Pur", "Mud Bhoora	");
        edu.aku.abdulsajid.VASMonitring.data.put("Khan Pur", "Mueenabad	");
        edu.aku.abdulsajid.VASMonitring.data.put("Khan Pur", "Nawan Kot	");
        edu.aku.abdulsajid.VASMonitring.data.put("Khan Pur", "Neel Garh	");
        edu.aku.abdulsajid.VASMonitring.data.put("Khan Pur", "Qadirpur	");
        edu.aku.abdulsajid.VASMonitring.data.put("Khan Pur", "Sehja	");
        edu.aku.abdulsajid.VASMonitring.data.put("Khan Pur", "UC-A Khanpur	");
        edu.aku.abdulsajid.VASMonitring.data.put("Khan Pur", "UC-B Khanpur	");
        edu.aku.abdulsajid.VASMonitring.data.put("Khan Pur", "UC-C Khanpur	");
        edu.aku.abdulsajid.VASMonitring.data.put("Khan Pur", "UC-D Khanpur	");
        edu.aku.abdulsajid.VASMonitring.data.put("Khan Pur", "UC-E Khanpur	");
        edu.aku.abdulsajid.VASMonitring.data.put("Khan Pur", "Zahir Pir	");
        edu.aku.abdulsajid.VASMonitring.data.put("Khipro", "Khori	");
        edu.aku.abdulsajid.VASMonitring.data.put("Khipro", "Khori	");
        edu.aku.abdulsajid.VASMonitring.data.put("Khipro", "Qazi Faiz Muhammad Rajar	");
        edu.aku.abdulsajid.VASMonitring.data.put("Khipro", "Manik Hingoro	");
        edu.aku.abdulsajid.VASMonitring.data.put("Khipro", "Qazi Faiz Muhammad Rajar	");
        edu.aku.abdulsajid.VASMonitring.data.put("Khipro", "Kamil Hingoro	");
        edu.aku.abdulsajid.VASMonitring.data.put("Khipro", "Qazi Faiz Muhammad Rajar	");
        edu.aku.abdulsajid.VASMonitring.data.put("Khipro", "Hathungo	");
        edu.aku.abdulsajid.VASMonitring.data.put("Khipro", "Khori	");
        edu.aku.abdulsajid.VASMonitring.data.put("Khipro", "Bilawal Hingorjo	");
        edu.aku.abdulsajid.VASMonitring.data.put("Khipro", "Bilawal Hingorjo	");
        edu.aku.abdulsajid.VASMonitring.data.put("Khipro", "Bilawal Hingorjo	");
        edu.aku.abdulsajid.VASMonitring.data.put("Khipro", "Dhilyar	");
        edu.aku.abdulsajid.VASMonitring.data.put("Khipro", "Bilawal Hingorjo	");
        edu.aku.abdulsajid.VASMonitring.data.put("Khipro", "Bilawal Hingorjo	");
        edu.aku.abdulsajid.VASMonitring.data.put("Khipro", "Khahi");
        edu.aku.abdulsajid.VASMonitring.data.put("Khipro", "Khahi");
        edu.aku.abdulsajid.VASMonitring.data.put("Khipro", "Roonjha");
        edu.aku.abdulsajid.VASMonitring.data.put("Khipro", "Kamil Hingoro");
        edu.aku.abdulsajid.VASMonitring.data.put("Khipro", "Roonjha");
        edu.aku.abdulsajid.VASMonitring.data.put("Khipro", "Khipro");
        edu.aku.abdulsajid.VASMonitring.data.put("Lakhra", "Lakhra");
        edu.aku.abdulsajid.VASMonitring.data.put("Lakhra", "Lakhra	");
        edu.aku.abdulsajid.VASMonitring.data.put("Lakhra", "Sheh	");
        edu.aku.abdulsajid.VASMonitring.data.put("Lakhra", "Lakhra	");
        edu.aku.abdulsajid.VASMonitring.data.put("Lakhra", "Liari	");
        edu.aku.abdulsajid.VASMonitring.data.put("Lakhra", "Liari	");
        edu.aku.abdulsajid.VASMonitring.data.put("Lakhra", "Liari	");
        edu.aku.abdulsajid.VASMonitring.data.put("Lakhra", "Lakhra	");
        edu.aku.abdulsajid.VASMonitring.data.put("Liaquat Pur", "Ahmed Ali Lar	");
        edu.aku.abdulsajid.VASMonitring.data.put("Liaquat Pur", "Allahabad	");
        edu.aku.abdulsajid.VASMonitring.data.put("Liaquat Pur", "Aminabad	");
        edu.aku.abdulsajid.VASMonitring.data.put("Liaquat Pur", "Chak No. 10 Abbasia	");
        edu.aku.abdulsajid.VASMonitring.data.put("Liaquat Pur", "Chak No. 178/7R	");
        edu.aku.abdulsajid.VASMonitring.data.put("Liaquat Pur", "Chak No. 42 Abbasia	");
        edu.aku.abdulsajid.VASMonitring.data.put("Liaquat Pur", "Chak No. 46 Abbasia	");
        edu.aku.abdulsajid.VASMonitring.data.put("Liaquat Pur", "Chak No. 68 Abbasia	");
        edu.aku.abdulsajid.VASMonitring.data.put("Liaquat Pur", "Chanjni	");
        edu.aku.abdulsajid.VASMonitring.data.put("Liaquat Pur", "Deshti	");
        edu.aku.abdulsajid.VASMonitring.data.put("Liaquat Pur", "Dulli Kabir Khan	");
        edu.aku.abdulsajid.VASMonitring.data.put("Liaquat Pur", "Ghooka	");
        edu.aku.abdulsajid.VASMonitring.data.put("Liaquat Pur", "Gul Mohammad Langah	");
        edu.aku.abdulsajid.VASMonitring.data.put("Liaquat Pur", "Hayat Lar	");
        edu.aku.abdulsajid.VASMonitring.data.put("Liaquat Pur", "Jan Pur	");
        edu.aku.abdulsajid.VASMonitring.data.put("Liaquat Pur", "Jhoke Ghulab Shah	");
        edu.aku.abdulsajid.VASMonitring.data.put("Liaquat Pur", "Khan Bela	");
        edu.aku.abdulsajid.VASMonitring.data.put("Liaquat Pur", "Liaquat Pur	");
        edu.aku.abdulsajid.VASMonitring.data.put("Liaquat Pur", "Mohammad Daha	");
        edu.aku.abdulsajid.VASMonitring.data.put("Liaquat Pur", "Mula Moosani	");
        edu.aku.abdulsajid.VASMonitring.data.put("Liaquat Pur", "Pacca Laran	");
        edu.aku.abdulsajid.VASMonitring.data.put("Liaquat Pur", "Shedani Sharif	");
        edu.aku.abdulsajid.VASMonitring.data.put("Liaquat Pur", "Trinda Gurgaj	");
        edu.aku.abdulsajid.VASMonitring.data.put("Liaquat Pur", "Trinda Mohammad Pannah	");
        edu.aku.abdulsajid.VASMonitring.data.put("Liaquat Pur", "Zafarabad	");
        edu.aku.abdulsajid.VASMonitring.data.put("Matli", "Haji Sawan	");
        edu.aku.abdulsajid.VASMonitring.data.put("Matli", "Thari	");
        edu.aku.abdulsajid.VASMonitring.data.put("Matli", "Budho Qambrani	");
        edu.aku.abdulsajid.VASMonitring.data.put("Matli", "Budho Qambrani	");
        edu.aku.abdulsajid.VASMonitring.data.put("Matli", "Manik Laghari	");
        edu.aku.abdulsajid.VASMonitring.data.put("Matli", "Malhan	");
        edu.aku.abdulsajid.VASMonitring.data.put("Matli", "Malhan	");
        edu.aku.abdulsajid.VASMonitring.data.put("Matli", "Manik Laghari	");
        edu.aku.abdulsajid.VASMonitring.data.put("Matli", "Ghulam Shah Laghari	");
        edu.aku.abdulsajid.VASMonitring.data.put("Matli", "Malhan	");
        edu.aku.abdulsajid.VASMonitring.data.put("Matli", "Matli-I	");
        edu.aku.abdulsajid.VASMonitring.data.put("Matli", "Matli-I	");
        edu.aku.abdulsajid.VASMonitring.data.put("Matli", "Budho Qambrani	");
        edu.aku.abdulsajid.VASMonitring.data.put("Matli", "Budho Qambrani	");
        edu.aku.abdulsajid.VASMonitring.data.put("Matli", "Dumbalo	");
        edu.aku.abdulsajid.VASMonitring.data.put("Matli", "Budho Qambrani	");
        edu.aku.abdulsajid.VASMonitring.data.put("Matli", "Budho Qambrani	");
        edu.aku.abdulsajid.VASMonitring.data.put("Matli", "Phalkara	");
        edu.aku.abdulsajid.VASMonitring.data.put("Matli", "Phalkara	");
        edu.aku.abdulsajid.VASMonitring.data.put("Matli", "Tando Ghulam Ali	");
        edu.aku.abdulsajid.VASMonitring.data.put("Matli", "Dumbalo	");
        edu.aku.abdulsajid.VASMonitring.data.put("Matli", "Dumbalo	");
        edu.aku.abdulsajid.VASMonitring.data.put("Matli", "Halepota	");
        edu.aku.abdulsajid.VASMonitring.data.put("Miro Khan", "Miro Khan	");
        edu.aku.abdulsajid.VASMonitring.data.put("Miro Khan", "Miro Khan	");
        edu.aku.abdulsajid.VASMonitring.data.put("Miro Khan", "Banbho Khan Chandio	");
        edu.aku.abdulsajid.VASMonitring.data.put("Miro Khan", "Behram	");
        edu.aku.abdulsajid.VASMonitring.data.put("Miro Khan", "Karira	");
        edu.aku.abdulsajid.VASMonitring.data.put("Miro Khan", "Karira	");
        edu.aku.abdulsajid.VASMonitring.data.put("Muzaffargarh", "Ahmed Mohana	");
        edu.aku.abdulsajid.VASMonitring.data.put("Muzaffargarh", "Aludaywall	");
        edu.aku.abdulsajid.VASMonitring.data.put("Muzaffargarh", "Basera (Muzaffargarh)	");
        edu.aku.abdulsajid.VASMonitring.data.put("Muzaffargarh", "Basti Karak	");
        edu.aku.abdulsajid.VASMonitring.data.put("Muzaffargarh", "Brahimwall	");
        edu.aku.abdulsajid.VASMonitring.data.put("Muzaffargarh", "Chak Ferazi	");
        edu.aku.abdulsajid.VASMonitring.data.put("Muzaffargarh", "Darain	");
        edu.aku.abdulsajid.VASMonitring.data.put("Muzaffargarh", "Ganga	");
        edu.aku.abdulsajid.VASMonitring.data.put("Muzaffargarh", "Garey Wahin	");
        edu.aku.abdulsajid.VASMonitring.data.put("Muzaffargarh", "Ghazangargarh	");
        edu.aku.abdulsajid.VASMonitring.data.put("Muzaffargarh", "Gul Wala	");
        edu.aku.abdulsajid.VASMonitring.data.put("Muzaffargarh", "Jaggat Pur	");
        edu.aku.abdulsajid.VASMonitring.data.put("Muzaffargarh", "Karamdad Qureshi	");
        edu.aku.abdulsajid.VASMonitring.data.put("Muzaffargarh", "Khangarh	");
        edu.aku.abdulsajid.VASMonitring.data.put("Muzaffargarh", "Khanpur Shumali	");
        edu.aku.abdulsajid.VASMonitring.data.put("Muzaffargarh", "Lutkaran	");
        edu.aku.abdulsajid.VASMonitring.data.put("Muzaffargarh", "Muzaffargarh City No. 1	");
        edu.aku.abdulsajid.VASMonitring.data.put("Muzaffargarh", "Muzaffargarh City No. 2	");
        edu.aku.abdulsajid.VASMonitring.data.put("Muzaffargarh", "Muzaffargarh City No. 3	");
        edu.aku.abdulsajid.VASMonitring.data.put("Muzaffargarh", "Manika Bhutta	");
        edu.aku.abdulsajid.VASMonitring.data.put("Muzaffargarh", "Mehra Sherqi	");
        edu.aku.abdulsajid.VASMonitring.data.put("Muzaffargarh", "Muzaffargarh City No. 4	");
        edu.aku.abdulsajid.VASMonitring.data.put("Muzaffargarh", "Minkpur	");
        edu.aku.abdulsajid.VASMonitring.data.put("Muzaffargarh", "Muradabad	");
        edu.aku.abdulsajid.VASMonitring.data.put("Muzaffargarh", "Nohanwali	");
        edu.aku.abdulsajid.VASMonitring.data.put("Muzaffargarh", "Rangpur	");
        edu.aku.abdulsajid.VASMonitring.data.put("Muzaffargarh", "Rohillanwali	");
        edu.aku.abdulsajid.VASMonitring.data.put("Muzaffargarh", "Shah Jamal	");
        edu.aku.abdulsajid.VASMonitring.data.put("Muzaffargarh", "Sharif Chajrah	");
        edu.aku.abdulsajid.VASMonitring.data.put("Muzaffargarh", "Taleeri	");
        edu.aku.abdulsajid.VASMonitring.data.put("Muzaffargarh", "Thatha Qureshi	");
        edu.aku.abdulsajid.VASMonitring.data.put("Muzaffargarh", "Umer Pur Janubi	");
        edu.aku.abdulsajid.VASMonitring.data.put("Muzaffargarh", "Usman Koria	");
        edu.aku.abdulsajid.VASMonitring.data.put("Muzaffargarh", "Uttra Sindeela	");
        edu.aku.abdulsajid.VASMonitring.data.put("Muzaffargarh", "Waah Pitafi	");
        edu.aku.abdulsajid.VASMonitring.data.put("Nasirabad", "Abad	");
        edu.aku.abdulsajid.VASMonitring.data.put("Nasirabad", "Nasirabad	");
        edu.aku.abdulsajid.VASMonitring.data.put("Nasirabad", "Nasirabad	");
        edu.aku.abdulsajid.VASMonitring.data.put("Nasirabad", "Dera	");
        edu.aku.abdulsajid.VASMonitring.data.put("Nasirabad", "Dera	");
        edu.aku.abdulsajid.VASMonitring.data.put("Nasirabad", "Dera	");
        edu.aku.abdulsajid.VASMonitring.data.put("Nasirabad", "Muradee	");
        edu.aku.abdulsajid.VASMonitring.data.put("Nasirabad", "Dera	");
        edu.aku.abdulsajid.VASMonitring.data.put("Nasirabad", "Lakha	");
        edu.aku.abdulsajid.VASMonitring.data.put("Nasirabad", "Gaji Khuhawarh	");
        edu.aku.abdulsajid.VASMonitring.data.put("Nasirabad", "Miandad Chinjni	");
        edu.aku.abdulsajid.VASMonitring.data.put("Nasirabad", "Miandad Chinjni	");
        edu.aku.abdulsajid.VASMonitring.data.put("Qambar", "Norang	");
        edu.aku.abdulsajid.VASMonitring.data.put("Qambar", "Beer	");
        edu.aku.abdulsajid.VASMonitring.data.put("Qambar", "Khair Pur Juso	");
        edu.aku.abdulsajid.VASMonitring.data.put("Qambar", "Khair Pur Juso	");
        edu.aku.abdulsajid.VASMonitring.data.put("Qambar", "Ranwati	");
        edu.aku.abdulsajid.VASMonitring.data.put("Qambar", "Chajhra	");
        edu.aku.abdulsajid.VASMonitring.data.put("Qambar", "Ranwati	");
        edu.aku.abdulsajid.VASMonitring.data.put("Qambar", "Jean Abro	");
        edu.aku.abdulsajid.VASMonitring.data.put("Qambar", "Jean Abro	");
        edu.aku.abdulsajid.VASMonitring.data.put("Qambar", "Norang	");
        edu.aku.abdulsajid.VASMonitring.data.put("Qambar", "Ghaibi Dero	");
        edu.aku.abdulsajid.VASMonitring.data.put("Qambar", "Kalar	");
        edu.aku.abdulsajid.VASMonitring.data.put("Qambar", "Booharh	");
        edu.aku.abdulsajid.VASMonitring.data.put("Qambar", "Booharh	");
        edu.aku.abdulsajid.VASMonitring.data.put("Qambar", "Booharh	");
        edu.aku.abdulsajid.VASMonitring.data.put("Qambar", "Beer	");
        edu.aku.abdulsajid.VASMonitring.data.put("Qambar", "Khair Pur Juso	");
        edu.aku.abdulsajid.VASMonitring.data.put("Qambar", "UC 2	");
        edu.aku.abdulsajid.VASMonitring.data.put("Qubo Saeed Khan", "Qubo Saeed Khan	");
        edu.aku.abdulsajid.VASMonitring.data.put("Qubo Saeed Khan", "Qubo Saeed Khan	");
        edu.aku.abdulsajid.VASMonitring.data.put("Qubo Saeed Khan", "Bago	");
        edu.aku.abdulsajid.VASMonitring.data.put("Rahim Yar Khan", "Abad Pur	");
        edu.aku.abdulsajid.VASMonitring.data.put("Rahim Yar Khan", "Akramabad	");
        edu.aku.abdulsajid.VASMonitring.data.put("Rahim Yar Khan", "Amin Garh	");
        edu.aku.abdulsajid.VASMonitring.data.put("Rahim Yar Khan", "Amin Garh	");
        edu.aku.abdulsajid.VASMonitring.data.put("Rahim Yar Khan", "Badli Sharif	");
        edu.aku.abdulsajid.VASMonitring.data.put("Rahim Yar Khan", "Bahdipur Qureshian	");
        edu.aku.abdulsajid.VASMonitring.data.put("Rahim Yar Khan", "Bahishti	");
        edu.aku.abdulsajid.VASMonitring.data.put("Rahim Yar Khan", "Bulaqi Wali	");
        edu.aku.abdulsajid.VASMonitring.data.put("Rahim Yar Khan", "Chak No. 105/P	");
        edu.aku.abdulsajid.VASMonitring.data.put("Rahim Yar Khan", "Chak No. 139/P	");
        edu.aku.abdulsajid.VASMonitring.data.put("Rahim Yar Khan", "Chak No. 228/P	");
        edu.aku.abdulsajid.VASMonitring.data.put("Rahim Yar Khan", "Chak No. 51/P	");
        edu.aku.abdulsajid.VASMonitring.data.put("Rahim Yar Khan", "Chak No. 84/P	");
        edu.aku.abdulsajid.VASMonitring.data.put("Rahim Yar Khan", "Dari Azim Khan	");
        edu.aku.abdulsajid.VASMonitring.data.put("Rahim Yar Khan", "Galor Masu Khan	");
        edu.aku.abdulsajid.VASMonitring.data.put("Rahim Yar Khan", "Haji Pur	");
        edu.aku.abdulsajid.VASMonitring.data.put("Rahim Yar Khan", "Kot Mehdi Shah	");
        edu.aku.abdulsajid.VASMonitring.data.put("Rahim Yar Khan", "Kot Samaba	");
        edu.aku.abdulsajid.VASMonitring.data.put("Rahim Yar Khan", "Mau Mubarak	");
        edu.aku.abdulsajid.VASMonitring.data.put("Rahim Yar Khan", "Mian Wali Qureshian	");
        edu.aku.abdulsajid.VASMonitring.data.put("Rahim Yar Khan", "Mianwali Shaikhan	");
        edu.aku.abdulsajid.VASMonitring.data.put("Rahim Yar Khan", "Murtazabad	");
        edu.aku.abdulsajid.VASMonitring.data.put("Rahim Yar Khan", "Rahim Yar Khan Deh	");
        edu.aku.abdulsajid.VASMonitring.data.put("Rahim Yar Khan", "Rajan Pur	");
        edu.aku.abdulsajid.VASMonitring.data.put("Rahim Yar Khan", "Shah Pur	");
        edu.aku.abdulsajid.VASMonitring.data.put("Rahim Yar Khan", "Shareen Kot Karam Khan	");
        edu.aku.abdulsajid.VASMonitring.data.put("Rahim Yar Khan", "Sonak	");
        edu.aku.abdulsajid.VASMonitring.data.put("Rahim Yar Khan", "Thul Khair	");
        edu.aku.abdulsajid.VASMonitring.data.put("Rahim Yar Khan", "Tibi gul Mohammad	");
        edu.aku.abdulsajid.VASMonitring.data.put("Rahim Yar Khan", "Tranda Saway Khan	");
        edu.aku.abdulsajid.VASMonitring.data.put("Rahim Yar Khan", "UC-A Rahim Yar Khan	");
        edu.aku.abdulsajid.VASMonitring.data.put("Rahim Yar Khan", "UC-B Rahim Yar Khan	");
        edu.aku.abdulsajid.VASMonitring.data.put("Rahim Yar Khan", "UC-C Rahim Yar Khan	");
        edu.aku.abdulsajid.VASMonitring.data.put("Rahim Yar Khan", "UC-D Rahim Yar Khan+	");
        edu.aku.abdulsajid.VASMonitring.data.put("Rahim Yar Khan", "UC-E Rahim Yar Khan+	");
        edu.aku.abdulsajid.VASMonitring.data.put("Rahim Yar Khan", "UC-F Rahim Yar Khan+	");
        edu.aku.abdulsajid.VASMonitring.data.put("Rahim Yar Khan", "UC-G Rahim Yar Khan+	");
        edu.aku.abdulsajid.VASMonitring.data.put("Rahim Yar Khan", "UC-H Rahim Yar Khan+	");
        edu.aku.abdulsajid.VASMonitring.data.put("Rahim Yar Khan", "UC-I Rahim Yar Khan+	");
        edu.aku.abdulsajid.VASMonitring.data.put("Rahim Yar Khan", "Waah Khuna	");
        edu.aku.abdulsajid.VASMonitring.data.put("Sadiqabad", "	Adam Sohaba	");
        edu.aku.abdulsajid.VASMonitring.data.put("Sadiqabad", "Ahmed Pur Lamma	");
        edu.aku.abdulsajid.VASMonitring.data.put("Sadiqabad", "Ahmed Pur Lamma (Urban)	");
        edu.aku.abdulsajid.VASMonitring.data.put("Sadiqabad", "Bhonga	");
        edu.aku.abdulsajid.VASMonitring.data.put("Sadiqabad", "Bhutta Wahan	");
        edu.aku.abdulsajid.VASMonitring.data.put("Sadiqabad", "Chak No. 160/P	");
        edu.aku.abdulsajid.VASMonitring.data.put("Sadiqabad", "Chak No. 173/P	");
        edu.aku.abdulsajid.VASMonitring.data.put("Sadiqabad", "Chak No. 264/P	");
        edu.aku.abdulsajid.VASMonitring.data.put("Sadiqabad", "Dhandi	");
        edu.aku.abdulsajid.VASMonitring.data.put("Sadiqabad", "Drigra	");
        edu.aku.abdulsajid.VASMonitring.data.put("Sadiqabad", "Goth Jangoo	");
        edu.aku.abdulsajid.VASMonitring.data.put("Sadiqabad", "Jamal din Wali	");
        edu.aku.abdulsajid.VASMonitring.data.put("Sadiqabad", "Kot Sanjar Khan	");
        edu.aku.abdulsajid.VASMonitring.data.put("Sadiqabad", "Machka	");
        edu.aku.abdulsajid.VASMonitring.data.put("Sadiqabad", "Mohib shah	");
        edu.aku.abdulsajid.VASMonitring.data.put("Sadiqabad", "Mohammad Pur	");
        edu.aku.abdulsajid.VASMonitring.data.put("Sadiqabad", "Nawabzada	");
        edu.aku.abdulsajid.VASMonitring.data.put("Sadiqabad", "Rahimabad	");
        edu.aku.abdulsajid.VASMonitring.data.put("Sadiqabad", "Ranjeh Khan	");
        edu.aku.abdulsajid.VASMonitring.data.put("Sadiqabad", "Rasool Pur	");
        edu.aku.abdulsajid.VASMonitring.data.put("Sadiqabad", "Roshan Bhait	");
        edu.aku.abdulsajid.VASMonitring.data.put("Sadiqabad", "Sadiqabad Deh	");
        edu.aku.abdulsajid.VASMonitring.data.put("Sadiqabad", "Sanja Pur	");
        edu.aku.abdulsajid.VASMonitring.data.put("Sadiqabad", "UC- A Sadiqabad	");
        edu.aku.abdulsajid.VASMonitring.data.put("Sadiqabad", "UC- B Sadiqabad	");
        edu.aku.abdulsajid.VASMonitring.data.put("Sadiqabad", "UC- C Sadiqabad	");
        edu.aku.abdulsajid.VASMonitring.data.put("Sadiqabad", "UC- D Sadiqabad	");
        edu.aku.abdulsajid.VASMonitring.data.put("Sadiqabad", "UC- E Sadiqabad	");
        edu.aku.abdulsajid.VASMonitring.data.put("Sadiqabad", "UC- F Sadiqabad	");
        edu.aku.abdulsajid.VASMonitring.data.put("Sanghar", "Sanghar	");
        edu.aku.abdulsajid.VASMonitring.data.put("Sanghar", "Shah Sikandarabad	");
        edu.aku.abdulsajid.VASMonitring.data.put("Sanghar", "Shah Sikandarabad	");
        edu.aku.abdulsajid.VASMonitring.data.put("Sanghar", "Shah Sikandarabad	");
        edu.aku.abdulsajid.VASMonitring.data.put("Sanghar", "Gujri	");
        edu.aku.abdulsajid.VASMonitring.data.put("Sanghar", "Chutyariyon	");
        edu.aku.abdulsajid.VASMonitring.data.put("Sanghar", "Chutyariyon	");
        edu.aku.abdulsajid.VASMonitring.data.put("Sanghar", "Karimdad Junijo	");
        edu.aku.abdulsajid.VASMonitring.data.put("Sanghar", "Miaan	");
        edu.aku.abdulsajid.VASMonitring.data.put("Sanghar", "Khadwari	");
        edu.aku.abdulsajid.VASMonitring.data.put("Sanghar", "Kanhar	");
        edu.aku.abdulsajid.VASMonitring.data.put("Sanghar", "Gujri	");
        edu.aku.abdulsajid.VASMonitring.data.put("Sanghar", "Pir Kehor	");
        edu.aku.abdulsajid.VASMonitring.data.put("Sanghar", "Sethar Pir	");
        edu.aku.abdulsajid.VASMonitring.data.put("Sanghar", "Sethar Pir	");
        edu.aku.abdulsajid.VASMonitring.data.put("Sanghar", "Piru Mal	");
        edu.aku.abdulsajid.VASMonitring.data.put("Sanghar", "Kandyari	");
        edu.aku.abdulsajid.VASMonitring.data.put("Sanghar", "Kandyari	");
        edu.aku.abdulsajid.VASMonitring.data.put("Shahdad Pur", "Barhoon	");
        edu.aku.abdulsajid.VASMonitring.data.put("Shahdad Pur", "Asgharabad	");
        edu.aku.abdulsajid.VASMonitring.data.put("Shahdad Pur", "Daim Khan Damraah	");
        edu.aku.abdulsajid.VASMonitring.data.put("Shahdad Pur", "Sarhari	");
        edu.aku.abdulsajid.VASMonitring.data.put("Shahdad Pur", "Daim Khan Damraah	");
        edu.aku.abdulsajid.VASMonitring.data.put("Shahdad Pur", "Sarhari	");
        edu.aku.abdulsajid.VASMonitring.data.put("Shahdad Pur", "Lundo	");
        edu.aku.abdulsajid.VASMonitring.data.put("Shahdad Pur", "Lundo	");
        edu.aku.abdulsajid.VASMonitring.data.put("Shahdad Pur", "Haji Koro Khan Umrani	");
        edu.aku.abdulsajid.VASMonitring.data.put("Shahdad Pur", "Soomar Faqir Hingro	");
        edu.aku.abdulsajid.VASMonitring.data.put("Shahdad Pur", "Asgharabad	");
        edu.aku.abdulsajid.VASMonitring.data.put("Shahdad Pur", "Asgharabad	");
        edu.aku.abdulsajid.VASMonitring.data.put("Shahdad Pur", "Soomar Faqir Hingro	");
        edu.aku.abdulsajid.VASMonitring.data.put("Shahdad Pur", "Soomar Faqir Hingro	");
        edu.aku.abdulsajid.VASMonitring.data.put("Shahdad Pur", "Soomar Faqir Hingro	");
        edu.aku.abdulsajid.VASMonitring.data.put("Shahdad Pur", "Shahdad Pur	");
        edu.aku.abdulsajid.VASMonitring.data.put("Shahdad Pur", "Maldasi	");
        edu.aku.abdulsajid.VASMonitring.data.put("Shahdad Pur", "Jama	");
        edu.aku.abdulsajid.VASMonitring.data.put("Shahdad Pur", "Shah Pur Chakar	");
        edu.aku.abdulsajid.VASMonitring.data.put("Shahdad Pur", "Haji Koro Khan Umrani	");
        edu.aku.abdulsajid.VASMonitring.data.put("Shahdad Pur", "Lundo	");
        edu.aku.abdulsajid.VASMonitring.data.put("Shahdadkot", "UC 3	");
        edu.aku.abdulsajid.VASMonitring.data.put("Shahdadkot", "Chakyani	");
        edu.aku.abdulsajid.VASMonitring.data.put("Shahdadkot", "Aitbar Khan Chandio	");
        edu.aku.abdulsajid.VASMonitring.data.put("Shahdadkot", "Aitbar Khan Chandio	");
        edu.aku.abdulsajid.VASMonitring.data.put("Shahdadkot", "Jamali	");
        edu.aku.abdulsajid.VASMonitring.data.put("Shahdadkot", "Jamali	");
        edu.aku.abdulsajid.VASMonitring.data.put("Shahdadkot", "UC 2");
        edu.aku.abdulsajid.VASMonitring.data.put("Shahpur Chakar", "Shahapur Chakar");
        edu.aku.abdulsajid.VASMonitring.data.put("Sijawal", "Sijawal");
        edu.aku.abdulsajid.VASMonitring.data.put("Sijawal", "Dhinghano Mahesar");
        edu.aku.abdulsajid.VASMonitring.data.put("Sijawal", "Sijawal");
        edu.aku.abdulsajid.VASMonitring.data.put("Sijawal", "Troop Chosool");
        edu.aku.abdulsajid.VASMonitring.data.put("Sijawal", "Hyder Chandio");
        edu.aku.abdulsajid.VASMonitring.data.put("Sijawal", "Troop chosool");
        edu.aku.abdulsajid.VASMonitring.data.put("Sijawal", "Mastoi");
        edu.aku.abdulsajid.VASMonitring.data.put("Sijawal", "Mastoi");
        edu.aku.abdulsajid.VASMonitring.data.put("Sijawal", "Mastoi");
        edu.aku.abdulsajid.VASMonitring.data.put("Sinjhoro", "Khadro");
        edu.aku.abdulsajid.VASMonitring.data.put("Sinjhoro", "Shah Mardanabad");
        edu.aku.abdulsajid.VASMonitring.data.put("Sinjhoro", "Deh 22 Jamrao");
        edu.aku.abdulsajid.VASMonitring.data.put("Sinjhoro", "Shah Mardanabad");
        edu.aku.abdulsajid.VASMonitring.data.put("Sinjhoro", "Sinjhoro");
        edu.aku.abdulsajid.VASMonitring.data.put("Sinjhoro", "Bitoor");
        edu.aku.abdulsajid.VASMonitring.data.put("Sinjhoro", "Kurkuli");
        edu.aku.abdulsajid.VASMonitring.data.put("Sinjhoro", "Jaffar Khan Laghari");
        edu.aku.abdulsajid.VASMonitring.data.put("Sinjhoro", "Shah Mardanabad");
        edu.aku.abdulsajid.VASMonitring.data.put("Sinjhoro", "Jhol");
        edu.aku.abdulsajid.VASMonitring.data.put("Sinjhoro", "Jhol");
        edu.aku.abdulsajid.VASMonitring.data.put("Sinjhoro", "Jhol");
        edu.aku.abdulsajid.VASMonitring.data.put("Sinjhoro", "Jhol");
        edu.aku.abdulsajid.VASMonitring.data.put("Sinjhoro", "Abbasabad	");
        edu.aku.abdulsajid.VASMonitring.data.put("Sinjhoro", "Wali Mohammad Kerio	");
        edu.aku.abdulsajid.VASMonitring.data.put("Sinjhoro", "Pir Sabgatullah Shah Shaheed");
        edu.aku.abdulsajid.VASMonitring.data.put("Sinjhoro", "Syed SabghutuAllah Shah Shaheed");
        edu.aku.abdulsajid.VASMonitring.data.put("Sinjhoro", "Pir Syed Sadruddin Shah Rashidi");
        edu.aku.abdulsajid.VASMonitring.data.put("Sinjhoro", "Pir Sabgatullah Shah Shaheed");
        edu.aku.abdulsajid.VASMonitring.data.put("Sinjhoro", "Pritam Abad	");
        edu.aku.abdulsajid.VASMonitring.data.put("Sonmiani", "Sonmiani");
        edu.aku.abdulsajid.VASMonitring.data.put("Sonmiani", "Sonmiani");
        edu.aku.abdulsajid.VASMonitring.data.put("Sonmiani", "Sonmiani");
        edu.aku.abdulsajid.VASMonitring.data.put("Sonmiani", "Sonmiani");
        edu.aku.abdulsajid.VASMonitring.data.put("Sonmiani", "Sonmiani");
        edu.aku.abdulsajid.VASMonitring.data.put("Talhar", "Piru Lashari	");
        edu.aku.abdulsajid.VASMonitring.data.put("Talhar", "Saeed Pur	");
        edu.aku.abdulsajid.VASMonitring.data.put("Talhar", "Talhar");
        edu.aku.abdulsajid.VASMonitring.data.put("Talhar", "Raju Khanani");
        edu.aku.abdulsajid.VASMonitring.data.put("Talhar", "Raju Khanani");
        edu.aku.abdulsajid.VASMonitring.data.put("Talhar", "Raju Khanani");
        edu.aku.abdulsajid.VASMonitring.data.put("Talhar", "Piru Lashari");
        edu.aku.abdulsajid.VASMonitring.data.put("Talhar", "Piru Lashari");
        edu.aku.abdulsajid.VASMonitring.data.put("Talhar", "Raju Khanani");
        edu.aku.abdulsajid.VASMonitring.data.put("Talhar", "Raju Khanani");
        edu.aku.abdulsajid.VASMonitring.data.put("Talhar", "Raju Khanani");
        edu.aku.abdulsajid.VASMonitring.data.put("Tamboo", "Khrose Wah");
        edu.aku.abdulsajid.VASMonitring.data.put("Tamboo", "Mir Behram Khan Buladi	");
        edu.aku.abdulsajid.VASMonitring.data.put("Tamboo", "Manjho Shori");
        edu.aku.abdulsajid.VASMonitring.data.put("Tamboo", "Khona Tamboo");
        edu.aku.abdulsajid.VASMonitring.data.put("Tamboo", "Khona Tamboo");
        edu.aku.abdulsajid.VASMonitring.data.put("Tamboo", "Khona Tamboo");
        edu.aku.abdulsajid.VASMonitring.data.put("Tamboo", "Mir Wah");
        edu.aku.abdulsajid.VASMonitring.data.put("Tamboo", "Allahabad	");
        edu.aku.abdulsajid.VASMonitring.data.put("Tamboo", "Abdullah Bari");
        edu.aku.abdulsajid.VASMonitring.data.put("Tamboo", "Khona Tamboo");
        edu.aku.abdulsajid.VASMonitring.data.put("Tamboo", "Abdullah Bari");
        edu.aku.abdulsajid.VASMonitring.data.put("Tamboo", "Khrose Wah");
        edu.aku.abdulsajid.VASMonitring.data.put("Tamboo", "Allahabad");
        edu.aku.abdulsajid.VASMonitring.data.put("Tamboo", "Allahabad");
        edu.aku.abdulsajid.VASMonitring.data.put("Tando Adam", "Manik Thaheem");
        edu.aku.abdulsajid.VASMonitring.data.put("Tando Adam", "Manik Thaheem");
        edu.aku.abdulsajid.VASMonitring.data.put("Tando Adam", "Manik Thaheem");
        edu.aku.abdulsajid.VASMonitring.data.put("Tando Adam", "Manik Thaheem");
        edu.aku.abdulsajid.VASMonitring.data.put("Tando Adam", "Kumb Darhoon");
        edu.aku.abdulsajid.VASMonitring.data.put("Tando Adam", "Kumb Darhoon");
        edu.aku.abdulsajid.VASMonitring.data.put("Tando Adam", "Kumb Darhoon");
        edu.aku.abdulsajid.VASMonitring.data.put("Tando Adam", "Kumb Darhoon");
        edu.aku.abdulsajid.VASMonitring.data.put("Tando Adam", "Kumb Darhoon");
        edu.aku.abdulsajid.VASMonitring.data.put("Tando Adam", "Mir Hassan Mari");
        edu.aku.abdulsajid.VASMonitring.data.put("Tando Adam", "Nothing Khoso");
        edu.aku.abdulsajid.VASMonitring.data.put("Tando Adam", "Mir Hassan Mari");
        edu.aku.abdulsajid.VASMonitring.data.put("Tando Adam", "Piro Faqir Shoro");
        edu.aku.abdulsajid.VASMonitring.data.put("Tando Adam", "Piro Faqir Shoro");
        edu.aku.abdulsajid.VASMonitring.data.put("Tando Adam", "Tando Adam");
        edu.aku.abdulsajid.VASMonitring.data.put("Tando Bago", "Khoskhi");
        edu.aku.abdulsajid.VASMonitring.data.put("Tando Bago", "Deh Jarkas");
        edu.aku.abdulsajid.VASMonitring.data.put("Tando Bago", "Khoskhi");
        edu.aku.abdulsajid.VASMonitring.data.put("Tando Bago", "Par Mari");
        edu.aku.abdulsajid.VASMonitring.data.put("Tando Bago", "Khalifo Qasim");
        edu.aku.abdulsajid.VASMonitring.data.put("Tando Bago", "Tando Bago");
        edu.aku.abdulsajid.VASMonitring.data.put("Tando Bago", "Khalifo Qasim");
        edu.aku.abdulsajid.VASMonitring.data.put("Tando Bago", "Khalifo Qasim");
        edu.aku.abdulsajid.VASMonitring.data.put("Tando Bago", "Khalifo Qasim");
        edu.aku.abdulsajid.VASMonitring.data.put("Tando Bago", "Khair Pur Gambo");
        edu.aku.abdulsajid.VASMonitring.data.put("Tando Bago", "Khair Pur");
        edu.aku.abdulsajid.VASMonitring.data.put("Tando Bago", "Pangrio");
        edu.aku.abdulsajid.VASMonitring.data.put("Tando Bago", "Pangrio");
        edu.aku.abdulsajid.VASMonitring.data.put("Tando Bago", "Khair Pur Gambo");
        edu.aku.abdulsajid.VASMonitring.data.put("Tando Bago", "Deh Jarkas");
        edu.aku.abdulsajid.VASMonitring.data.put("Tando Bago", "Pangrio");
        edu.aku.abdulsajid.VASMonitring.data.put("Tando Bago", "Chabralo");
        edu.aku.abdulsajid.VASMonitring.data.put("Tando Bago", "Dadah");
        edu.aku.abdulsajid.VASMonitring.data.put("Tando Bago", "Dadah");
        edu.aku.abdulsajid.VASMonitring.data.put("Tando Bago", "Dadah");
        edu.aku.abdulsajid.VASMonitring.data.put("Tando Bago", "Dadah");
        edu.aku.abdulsajid.VASMonitring.data.put("Tando Bago", "Dadah");
        edu.aku.abdulsajid.VASMonitring.data.put("Tando Bago", "Khadro");
        edu.aku.abdulsajid.VASMonitring.data.put("Tando Bago", "Khadro");
        edu.aku.abdulsajid.VASMonitring.data.put("Tando Bago", "Dadah");
        edu.aku.abdulsajid.VASMonitring.data.put("Usta Muhammad", "	UC 4");
        edu.aku.abdulsajid.VASMonitring.data.put("Usta Muhammad", "	UC 2");
        edu.aku.abdulsajid.VASMonitring.data.put("Usta Muhammad", "	Khan Pur 	");
        edu.aku.abdulsajid.VASMonitring.data.put("Usta Muhammad", "	Ali Abad Jamali");
        edu.aku.abdulsajid.VASMonitring.data.put("Usta Muhammad", "	Faizabad Jamali");
        edu.aku.abdulsajid.VASMonitring.data.put("Usta Muhammad", "	Faizabad Jamali");
        edu.aku.abdulsajid.VASMonitring.data.put("Usta Muhammad", "	Faizabad Jamali");
        edu.aku.abdulsajid.VASMonitring.data.put("Usta Muhammad", "	Khan Pur Jamali");
        edu.aku.abdulsajid.VASMonitring.data.put("Usta Muhammad", "	UC 2");
        edu.aku.abdulsajid.VASMonitring.data.put("Usta Muhammad", "	Hadeero");
        edu.aku.abdulsajid.VASMonitring.data.put("Usta Muhammad", "	Ali Abad Jamali");
        edu.aku.abdulsajid.VASMonitring.data.put("Usta Muhammad", "	Qaboola");
        edu.aku.abdulsajid.VASMonitring.data.put("Usta Muhammad", "	Peeralabad");
        edu.aku.abdulsajid.VASMonitring.data.put("Usta Muhammad", "	Peeralabad");
        edu.aku.abdulsajid.VASMonitring.data.put("Usta Muhammad", "	Chalgri");
        edu.aku.abdulsajid.VASMonitring.data.put("Usta Muhammad", "	Qaboola");
        edu.aku.abdulsajid.VASMonitring.data.put("Usta Muhammad", "	Sameji");
        edu.aku.abdulsajid.VASMonitring.data.put("Usta Muhammad", "	Ali Abad Jamali");
        edu.aku.abdulsajid.VASMonitring.data.put("Usta Muhammad", "	Ali Abad Jamali");
        edu.aku.abdulsajid.VASMonitring.data.put("Uthal", "Uthal");
        edu.aku.abdulsajid.VASMonitring.data.put("Uthal", "Wayaro");
        edu.aku.abdulsajid.VASMonitring.data.put("Uthal", "Uthal");
        edu.aku.abdulsajid.VASMonitring.data.put("Uthal", "Kichnwari");
        edu.aku.abdulsajid.VASMonitring.data.put("Uthal", "Wayaro");
        edu.aku.abdulsajid.VASMonitring.data.put("Uthal", "Wayaro");
        edu.aku.abdulsajid.VASMonitring.data.put("Warah", "Wagan");
        edu.aku.abdulsajid.VASMonitring.data.put("Warah", "Warah");
        edu.aku.abdulsajid.VASMonitring.data.put("Warah", "Lalu Raunk");
        edu.aku.abdulsajid.VASMonitring.data.put("Warah", "Abad	");
        edu.aku.abdulsajid.VASMonitring.data.put("Warah", "Wagan");
        edu.aku.abdulsajid.VASMonitring.data.put("Warah", "Abad");
        edu.aku.abdulsajid.VASMonitring.data.put("Warah", "Mir Pur");
        edu.aku.abdulsajid.VASMonitring.data.put("Warah", "Khandu");
        edu.aku.abdulsajid.VASMonitring.data.put("Warah", "Gaji Khuhawarh");
        edu.aku.abdulsajid.VASMonitring.data.put("Warah", "Gaji Khuhawarh");
        edu.aku.abdulsajid.VASMonitring.data.put("Warah", "Khandu");

        edu.aku.abdulsajid.VASMonitring.data.put("Gulshan-e-Iqbal", "Gulzar Hijri");
        edu.aku.abdulsajid.VASMonitring.data.put("Gulshan-e-Iqbal", "Pehlwan Goath");

        edu.aku.abdulsajid.VASMonitring.data.put("Korangi", "Nasir Colony");


        List<String> list = new ArrayList<>();
        Collection<String> coll = edu.aku.abdulsajid.VASMonitring.data.get(tehsil);

        list.add("Select");
        for (String item : coll) {
            list.add(item);
        }


        return list;*/



    /*    // Creating adapter for spinner
        ArrayAdapter<String> dataAdapter = new ArrayAdapter<String>(getActivity(),
         android.R.layout.simple_spinner_item, list_UC);

        // Drop down layout style - list view with radio button
        dataAdapter.setDropDownViewResource(android.R.layout.simple_spinner_dropdown_item);

        // attaching edu.aku.abdulsajid.VASMonitring.data adapter to spinner
        sp_UC.setAdapter(dataAdapter);
        sp_UC.setSelection(coll_district.size());*/

//    }

}
